name: NoPhantoms
version: '${project.version}'
main: org.chinmay.nophantoms.NoPhantoms
api-version: '1.21'
authors: [chinmay]
description: Removes phantoms completely from your server!
website: spigot.chinmay.lol
